"""Compatibility exports for shared reducer helpers."""

import platform as _platform_module

from .entry_state_helpers import current_entry_for_path, single_target_entry
from .reducer_config import (
    CONFIG_EDITOR_CATEGORIES,
    CONFIG_EDITOR_COMMANDS,
    CONFIG_LOG_LEVELS,
    CONFIG_PASTE_ACTIONS,
    CONFIG_PREVIEW_MAX_KIB,
    CONFIG_PREVIEW_SYNTAX_THEMES,
    CONFIG_SORT_FIELDS,
    CONFIG_THEMES,
    apply_config_to_runtime_state,
    config_editor_field_ids,
    config_editor_labels,
    config_editor_visual_order,
    cycle_choice,
    cycle_config_editor_value,
    cycle_editor_command,
    move_config_cursor_visual,
    normalize_config_editor_cursor,
)
from .reducer_pane_sync import (
    directory_size_cache_by_path,
    directory_size_target_paths,
    maybe_request_directory_sizes,
    normalize_child_pane_for_display,
    sync_child_pane,
    upsert_directory_size_entries,
    visible_directory_paths,
)
from .reducer_path_helpers import (
    REGEX_FILE_SEARCH_PREFIX,
    REGEX_GREP_SEARCH_PREFIX,
    active_current_entries,
    current_entry_paths,
    expand_and_validate_path,
    filter_file_search_results,
    format_go_to_path_completion,
    is_regex_file_search_query,
    list_matching_directory_paths,
    move_cursor,
    normalize_cursor_path,
    normalize_selected_paths,
    normalize_selection_anchor_path,
    select_range_paths,
)
from .reducer_pending_input import (
    build_extract_archive_request,
    build_file_mutation_request,
    build_zip_compress_request,
    complete_pending_input_path,
    is_name_conflict_validation_error,
    is_symlink_destination_conflict_validation_error,
    name_conflict_kind,
    pending_input_parent_and_target,
    resolve_pending_input_base_path,
    resolve_pending_input_destination_path,
)
from .reducer_pending_input import (
    validate_pending_input as _validate_pending_input,
)
from .reducer_requests import (
    ReducerFn,
    browser_snapshot_invalidation_paths,
    build_history_after_snapshot_load,
    cursor_path_after_file_mutation,
    finalize,
    format_clipboard_message,
    notification_for_external_launch,
    notification_for_paste_summary,
    request_snapshot_refresh,
    restore_ui_mode_after_pending_input,
    run_archive_extract_request,
    run_archive_prepare_request,
    run_external_launch_request,
    run_file_mutation_request,
    run_paste_request,
    run_undo_request,
    run_zip_compress_prepare_request,
    run_zip_compress_request,
)

_is_macos = _platform_module.system() == "Darwin"

__all__ = [
    "CONFIG_EDITOR_CATEGORIES",
    "CONFIG_EDITOR_COMMANDS",
    "CONFIG_LOG_LEVELS",
    "CONFIG_PASTE_ACTIONS",
    "CONFIG_PREVIEW_MAX_KIB",
    "CONFIG_PREVIEW_SYNTAX_THEMES",
    "CONFIG_SORT_FIELDS",
    "CONFIG_THEMES",
    "REGEX_FILE_SEARCH_PREFIX",
    "REGEX_GREP_SEARCH_PREFIX",
    "ReducerFn",
    "_is_macos",
    "active_current_entries",
    "apply_config_to_runtime_state",
    "browser_snapshot_invalidation_paths",
    "build_extract_archive_request",
    "build_file_mutation_request",
    "build_history_after_snapshot_load",
    "build_zip_compress_request",
    "complete_pending_input_path",
    "config_editor_field_ids",
    "config_editor_labels",
    "config_editor_visual_order",
    "current_entry_for_path",
    "current_entry_paths",
    "cursor_path_after_file_mutation",
    "cycle_choice",
    "cycle_config_editor_value",
    "cycle_editor_command",
    "directory_size_cache_by_path",
    "directory_size_target_paths",
    "expand_and_validate_path",
    "filter_file_search_results",
    "finalize",
    "format_clipboard_message",
    "format_go_to_path_completion",
    "is_name_conflict_validation_error",
    "is_regex_file_search_query",
    "is_symlink_destination_conflict_validation_error",
    "list_matching_directory_paths",
    "maybe_request_directory_sizes",
    "move_config_cursor_visual",
    "move_cursor",
    "name_conflict_kind",
    "normalize_child_pane_for_display",
    "normalize_config_editor_cursor",
    "normalize_cursor_path",
    "normalize_selected_paths",
    "normalize_selection_anchor_path",
    "notification_for_external_launch",
    "notification_for_paste_summary",
    "pending_input_parent_and_target",
    "request_snapshot_refresh",
    "resolve_pending_input_base_path",
    "resolve_pending_input_destination_path",
    "restore_ui_mode_after_pending_input",
    "run_archive_extract_request",
    "run_archive_prepare_request",
    "run_external_launch_request",
    "run_file_mutation_request",
    "run_paste_request",
    "run_undo_request",
    "run_zip_compress_prepare_request",
    "run_zip_compress_request",
    "select_range_paths",
    "single_target_entry",
    "single_target_path",
    "sync_child_pane",
    "upsert_directory_size_entries",
    "validate_pending_input",
    "visible_directory_paths",
]


def validate_pending_input(state) -> str | None:
    return _validate_pending_input(state, is_macos=_is_macos)


def single_target_path(state) -> str | None:
    entry = single_target_entry(state)
    return entry.path if entry else None
