"""Preview loading helpers and loader implementations."""

from .core import (
    DEFAULT_GREP_CONTEXT_WINDOW_LOOKAHEAD_LINES,
    DEFAULT_IMAGE_PREVIEW_COLUMNS,
    GREP_PREVIEW_ERROR_MESSAGE,
    IMAGE_PREVIEW_DEPENDENCY_MESSAGE,
    PREVIEW_ERROR_MESSAGE,
    PREVIEW_PERMISSION_DENIED_MESSAGE,
    PREVIEW_UNSUPPORTED_MESSAGE,
    TEXT_PREVIEW_MAX_BYTES,
    ChafaImagePreviewLoader,
    ContextPreviewState,
    DocumentPreviewLoader,
    FilePreviewState,
    GrepContextCacheKey,
    GrepContextWindowCacheKey,
    GrepContextWindowState,
    ImagePreviewLoader,
    PandocDocumentPreviewLoader,
    _build_grep_context_cache_key,
    _build_grep_context_preview_from_window,
    _build_text_preview_cache_key,
    _is_preview_candidate,
    _load_grep_context_preview,
    _load_grep_context_window,
    _load_text_preview,
    preview_max_bytes_from_kib,
)

__all__ = [
    "ChafaImagePreviewLoader",
    "ContextPreviewState",
    "DEFAULT_IMAGE_PREVIEW_COLUMNS",
    "DEFAULT_GREP_CONTEXT_WINDOW_LOOKAHEAD_LINES",
    "DocumentPreviewLoader",
    "FilePreviewState",
    "GREP_PREVIEW_ERROR_MESSAGE",
    "GrepContextCacheKey",
    "GrepContextWindowCacheKey",
    "GrepContextWindowState",
    "IMAGE_PREVIEW_DEPENDENCY_MESSAGE",
    "ImagePreviewLoader",
    "PandocDocumentPreviewLoader",
    "PREVIEW_ERROR_MESSAGE",
    "PREVIEW_PERMISSION_DENIED_MESSAGE",
    "PREVIEW_UNSUPPORTED_MESSAGE",
    "TEXT_PREVIEW_MAX_BYTES",
    "_build_grep_context_cache_key",
    "_build_grep_context_preview_from_window",
    "_build_text_preview_cache_key",
    "_is_preview_candidate",
    "_load_grep_context_preview",
    "_load_grep_context_window",
    "_load_text_preview",
    "preview_max_bytes_from_kib",
]
