"""State management primitives."""

from .actions import (
    Action,
    BeginFilterInput,
    BrowserSnapshotFailed,
    BrowserSnapshotLoaded,
    CancelFilterInput,
    ChildPaneSnapshotFailed,
    ChildPaneSnapshotLoaded,
    ClearSelection,
    ConfirmFilterInput,
    InitializeState,
    MoveCursor,
    RequestBrowserSnapshot,
    SetCursorPath,
    SetFilterQuery,
    SetFilterRecursive,
    SetNotification,
    SetSort,
    SetUiMode,
    ToggleSelection,
    ToggleSelectionAndAdvance,
)
from .effects import Effect, LoadBrowserSnapshotEffect, LoadChildPaneSnapshotEffect, ReduceResult
from .input import dispatch_key_input
from .models import (
    AppState,
    BrowserSnapshot,
    ClipboardState,
    DirectoryEntryState,
    FilterState,
    HistoryState,
    NotificationState,
    PaneState,
    SortState,
    UiMode,
    build_initial_app_state,
    build_placeholder_app_state,
)
from .reducer import reduce_app_state
from .selectors import (
    select_child_entries,
    select_current_entries,
    select_parent_entries,
    select_shell_data,
    select_status_bar_state,
    select_visible_current_entry_states,
)

__all__ = [
    "Action",
    "AppState",
    "BeginFilterInput",
    "BrowserSnapshot",
    "BrowserSnapshotFailed",
    "BrowserSnapshotLoaded",
    "CancelFilterInput",
    "ChildPaneSnapshotFailed",
    "ChildPaneSnapshotLoaded",
    "ClearSelection",
    "ClipboardState",
    "ConfirmFilterInput",
    "DirectoryEntryState",
    "Effect",
    "FilterState",
    "HistoryState",
    "InitializeState",
    "LoadBrowserSnapshotEffect",
    "LoadChildPaneSnapshotEffect",
    "MoveCursor",
    "NotificationState",
    "PaneState",
    "ReduceResult",
    "RequestBrowserSnapshot",
    "SetCursorPath",
    "SetFilterQuery",
    "SetFilterRecursive",
    "SetNotification",
    "SetSort",
    "SetUiMode",
    "SortState",
    "ToggleSelection",
    "ToggleSelectionAndAdvance",
    "UiMode",
    "build_initial_app_state",
    "build_placeholder_app_state",
    "dispatch_key_input",
    "reduce_app_state",
    "select_child_entries",
    "select_current_entries",
    "select_parent_entries",
    "select_shell_data",
    "select_status_bar_state",
    "select_visible_current_entry_states",
]
