"""State management primitives."""

from .actions import (
    Action,
    ClearSelection,
    InitializeState,
    MoveCursor,
    SetCursorPath,
    SetFilterQuery,
    SetFilterRecursive,
    SetSort,
    SetStatusMessage,
    SetUiMode,
    ToggleSelection,
)
from .models import (
    AppState,
    ClipboardState,
    DirectoryEntryState,
    FilterState,
    HistoryState,
    PaneState,
    SortState,
    UiMode,
    build_initial_app_state,
)
from .reducer import reduce_app_state
from .selectors import (
    select_child_entries,
    select_current_entries,
    select_parent_entries,
    select_shell_data,
    select_status_bar_state,
    select_visible_current_entry_states,
)

__all__ = [
    "Action",
    "AppState",
    "ClearSelection",
    "ClipboardState",
    "DirectoryEntryState",
    "FilterState",
    "HistoryState",
    "InitializeState",
    "MoveCursor",
    "PaneState",
    "SetCursorPath",
    "SetFilterQuery",
    "SetFilterRecursive",
    "SetSort",
    "SetStatusMessage",
    "SetUiMode",
    "SortState",
    "ToggleSelection",
    "UiMode",
    "build_initial_app_state",
    "reduce_app_state",
    "select_child_entries",
    "select_current_entries",
    "select_parent_entries",
    "select_shell_data",
    "select_status_bar_state",
    "select_visible_current_entry_states",
]
